language: r
pandoc_version: 1.19.2.1
sudo: required
cache:
  packages: true
before_install:
- sudo apt-get install libv8-dev 
before_script:
- chmod +x ./_build.sh
- git config --global user.email "christoph.molnar@gmail.com"
- git config --global user.name "Christoph Molnar"
script: ./_build.sh

